### ISSUE TITLE
希望作者能尽快将使用文档补全,非常感谢

### ISSUE THREAD

**Issue by coderiy** [kxzxvbk/Fling#21]
如题

**Comment by kxzxvbk** [comment]
Sure, we will soon update the document in Chinese. Currently, you may read the documents in English.
In the [document](https://github.com/kxzxvbk/Fling/tree/main/docs) folder, files end with "zh.md" are written in Chinese, which are to be done. Files end with "en.md" are written in English, which are already roughly completed.
If you are still cofused after reading the documents, feel free to propose your question here. :)

**Comment by kxzxvbk** [comment]
Chinese docs except "how to add a new FL algorithm" are already merged into the main branch now. Please refer to our latest version.
