### ISSUE TITLE
怎么解决这个bug？当我run fedcac时候遇到的

### ISSUE THREAD

**Issue by cqycqy1999** [kxzxvbk/Fling#40]
![image](https://github.com/kxzxvbk/Fling/assets/50649718/801d7746-6ef7-4f66-b4a7-4d44115fcef1)

**Comment by kxzxvbk** [comment]
It seems to relate to something about multiprocessing. A direct way is to prevent it is to add ``launcher=dict(name='serial'),`` in your config file, although it may slow down the training speed. We are working to solve this bug !

**Comment by kxzxvbk** [comment]
Bug resolved in #41 . Please update Fling to the newest version.
